name: Deploy

on:
  push:
  schedule:
  - cron: "0 7 * * *"
 
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Build apps
      uses: hyoo-ru/mam_build@master2
      with:
        package: hyoo/bench
        modules: bench list/mol list/tsx list/tsxatom chart/rope/mol chart/bar/mol 
        
    - name: Consolidate apps
      run: |
        mkdir ./-
        mkdir ./-/list
        mv hyoo/bench/bench/- ./-/bench
        mv hyoo/bench/list/angularjs ./-/list
        mv hyoo/bench/list/native-html ./-/list
        mv hyoo/bench/list/react ./-/list
        mv hyoo/bench/list/sapui5 ./-/list
        mv hyoo/bench/list/mol/- ./-/list/mol
        mv hyoo/bench/list/tsx/- ./-/list/tsx
        mv hyoo/bench/list/tsxatom/- ./-/list/tsxatom
        mv hyoo/bench/geometry ./-
        mv hyoo/bench/elements ./-
        mkdir ./-/chart
        mkdir ./-/chart/bar
        mv hyoo/bench/chart/bar/anychart ./-/chart/bar
        mv hyoo/bench/chart/bar/hcharts ./-/chart/bar
        mv hyoo/bench/chart/bar/mol/- ./-/chart/bar/mol
        mkdir ./-/chart/rope
        mv hyoo/bench/chart/bar/anychart ./-/chart/rope
        mv hyoo/bench/chart/bar/canvasjs ./-/chart/rope
        mv hyoo/bench/chart/bar/hcharts ./-/chart/rope
        mv hyoo/bench/chart/bar/mol/- ./-/chart/rope/mol
    
    - name: Deploy on GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: ./-
